*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:22  eugenio
* Initial revision
*
* Revision 1.1.1.1  1994/04/05  21:38:30  lkg
* Beta version of GEANT using CLEO CVS system
*
*
*CMZ :  3.15/02 25/03/92  08.57.50  by  Federico Carminati
*-- Author :
*-- Author :
******  CG package (Graphics Package for Solid Combine Geometry)  ******
************************************************************************
*                                                                      *
*       CG - PACKAGE  Virsion 1.02                                     *
*                                                                      *
*       E.V. CHERNYAEV ( EC )   , IHEP, PROTVINO, 1988 - 1989          *
*                                                                      *
************************************************************************
