*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:22  eugenio
* Initial revision
*
* Revision 1.1.1.1  1994/04/05  21:38:30  lkg
* Beta version of GEANT using CLEO CVS system
*
*
*
* cghpar.inc
*
      PARAMETER (I4SIZE = 1)
      PARAMETER (LHHEAD=18,KHSIZE=1)
      PARAMETER (          KHNT  =2)
      PARAMETER (          KHIFWI=3)
      PARAMETER (          KHNXYZ=8)
      PARAMETER (          KHNFAC=9)
      PARAMETER (          KHNEDG=10)
      PARAMETER (          KHJXYZ=11)
      PARAMETER (          KHJFA =12)
      PARAMETER (          KHJPFA=13)
      PARAMETER (          KHJDFA=14)
      PARAMETER (          KHJTRE=15)
      PARAMETER (          KHJSTA=16)
      PARAMETER (          KHJALE=17)
      PARAMETER (          KHJARI=18)
