*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:37  eugenio
* Initial revision
*
* Revision 1.1.1.1  1994/10/08  02:21:36  zfiles
* first version of qqlib in CVS
*
*
*CMZ :  1.03/15 25/04/91  18.23.44  by  R.A.FULTON
*-- Author :    R.A.FULTON   04/12/90
        REAL     ALPHA, HALFPI, PI, PIINV, TWOPI, XME
        PARAMETER (  ALPHA   = 0.00729735)
        PARAMETER (  HALFPI  = 1.570796 )
        PARAMETER (  PI      = 3.141592 )
        PARAMETER (  PIINV   = 0.31830989)
        PARAMETER (  TWOPI   = 6.283185 )
        PARAMETER (  XME     = 0.000511)

