*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:10  eugenio
* Initial revision
*
* Revision 1.1.1.1  1995/08/01  17:59:28  nk
* Consolidation
*
* Revision 1.1.1.1  1994/10/04 21:54:48  zfiles
* first version of clutil in CVS
*
*
*CMZ :  1.00/05 27/07/89  13.54.08  by  B. Heltsley
*-- Author :    B. Heltsley   21/07/89

      INTEGER     OFSTML
      PARAMETER ( OFSTML = 1 )

      INTEGER     OFDIMS
      PARAMETER ( OFDIMS = 3 )

      INTEGER     OFCLDI
      PARAMETER ( OFCLDI = 7 )

      INTEGER     OFMSHS,     OFMSHI,     OFMSHW,     OFMSHE
      PARAMETER ( OFMSHS = 1, OFMSHI = 2, OFMSHW = 3, OFMSHE = 4 )
      INTEGER     OFMSHF,     OFMSHA
      PARAMETER ( OFMSHF = 5, OFMSHA = 6 )

      INTEGER     OFMSTS,     OFMSTI,     OFMSTW,     OFMSTE
      PARAMETER ( OFMSTS = 1, OFMSTI = 1, OFMSTW = 1, OFMSTE = 1 )
      INTEGER     OFMSTF,     OFMSTA
      PARAMETER ( OFMSTF = 1, OFMSTA = 1 )

      INTEGER     OFMLHS,     OFMLHI,     OFMLHW,     OFMLHE
      PARAMETER ( OFMLHS = 1, OFMLHI = 2, OFMLHW = 3, OFMLHE = 4 )
      INTEGER     OFMLHF,     OFMLHA
      PARAMETER ( OFMLHF = 5, OFMLHA = 6 )

      INTEGER     OFMLTS,     OFMLTI,     OFMLTW,     OFMLTE
      PARAMETER ( OFMLTS = 1, OFMLTI = 1, OFMLTW = 1, OFMLTE = 1 )
      INTEGER     OFMLTF,     OFMLTA
      PARAMETER ( OFMLTF = 1, OFMLTA = 1 )

      INTEGER     OFMSOS,     OFMSOI,     OFMSOW,     OFMSOE
      PARAMETER ( OFMSOS = 2, OFMSOI = 2, OFMSOW = 2, OFMSOE = 2 )
      INTEGER     OFMSOF,     OFMSOA
      PARAMETER ( OFMSOF = 2, OFMSOA = 2 )
