*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:10  eugenio
* Initial revision
*
* Revision 1.1.1.1  1995/08/01  17:59:28  nk
* Consolidation
*
* Revision 1.1.1.1  1994/10/04 21:54:49  zfiles
* first version of clutil in CVS
*
*
* Documentation for DDNMSP
*
* ddnmspdo.inc
*
*
* NOLNER - No logical name present error
* LNTRER - Logical name truncated  error
* LNICER - Logical name has invalid character error
* VXFPER - Error from VXFPRS
* FNMSER - File name missing error
* FTMSER - File type missing error
* FNTRER - File name truncated error
* FTTRER - File type truncated error
* FNICER - File name has invalid character error
* FTICER - File type has invalid character error
* NDCBER - No DCB information present error
* ASSMSG - Issue message on what is being assigned
* ASSIER - Error attempting to assign   logical name
* DEAMSG - Issue message on what is being deassigned
* DEASER - Error attempting to deassign logical name
* FTLMSG - Issue fatal error message
* NOERRS - No error
* RETERR - Return immediately
* DDCERR - Call DDNCLR
* LNAMSG - Issue logical name assumed message
* LLSMSG - Issue log level set message
* NODDMS - Number of DDNAME messages
* ICLOGL - Current log level
* LOGLMS - Log level for each message
*
