*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:10  eugenio
* Initial revision
*
* Revision 1.1.1.1  1995/08/01  17:59:31  nk
* Consolidation
*
* Revision 1.1.1.1  1994/10/04 21:54:49  zfiles
* first version of clutil in CVS
*
*
*CMZ :  1.00/30 07/11/90  13.05.22  by  B. Heltsley
* add LPT to output units
*CMZ :          17/05/89  12.22.53  by  CLEO II Librarian
*CMZ :  1.00/00 04/04/89  12.06.45  by  R. Namjoshi
*-- Author :    R. Namjoshi   18/07/88
