
PACKAGES = DANA:ROOT


CXXFLAGS += -I/group/da/ejw/coda/include
###LD_FLAGS += -L/group/da/ejw/coda/Linux-i686/lib -levioxx -levio -lexpat
LD_LIBS += -L/group/da/ejw/coda/Linux-x86_64/lib -levioxx -levio -lexpat


include $(HALLD_HOME)/src/BMS/Makefile.shlib


