*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:52  eugenio
* Initial revision
*
* Revision 1.2  1994/10/07  23:58:35  zfiles
* Include qqxxxx.inc
*
*
*CMZ :  1.02/61 03/10/94  17.28.08  by  Paul Avery
*CMZ :  1.02/29 01/12/92  15.00.03  by  Nobu Katayama
*CMZ :  1.02/00 25/07/91  13.56.14  by  Peter C Kim
*CMZ :  1.01/86 28/02/91  17.46.37  by  Karen Lingel, Physicist
*CMZ :  1.01/67 03/11/90  17.42.20  by  Paul Avery
*CMZ :          19/05/90  13.53.08  by  Jorge L. Rodriguez
*>> Author :
#if defined(CLEO_CDGDOC)
C  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
C
C                         MCPARS.INC
C
C   Contains parameters needed for dimension statements in QQ. This file
C   is essentially the same as the old one with a few additions.
C
C       MCPARS  <==  //seq/clinc/qqpars               9/94 PRA
C  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#endif

#include "seq/clinc/qqpars.inc"
