*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:52  eugenio
* Initial revision
*
* Revision 1.1  1994/10/07  23:57:33  zfiles
* New include files for QQ.
*
*
*CMZ :  1.02/61 03/10/94  17.34.50  by  Paul Avery
*CMZ :          08/10/93  16.07.05  by  Paul Avery
*>> Author :
*
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*                      QQBFLD.INC
*
*                      QQ B field
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*
#if defined(CLEO_CDGDOC)
*  BFLDQQ              B field in KG (NOT Tesla)
#endif

      REAL BFLDQQ
      COMMON/QQBFL1/
     *   BFLDQQ

