*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:52  eugenio
* Initial revision
*
* Revision 1.1  1994/10/07  23:57:38  zfiles
* New include files for QQ.
*
*
*CMZ :  1.02/61 03/10/94  17.35.08  by  Paul Avery
*CMZ :          08/10/93  16.00.06  by  Paul Avery
*>> Author :
*
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*                         QQIPFT.INC
*
*         Points from full track list to FTMONTE track.
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*
#if defined(CLEO_CDGDOC)
*  IPCDFT(IT)          FTMONTE track number (0 if none)
#endif

      INTEGER IPFTQQ
      COMMON/QQIPF1/
     *   IPFTQQ(MCTRK)
