#ifndef HIT_TRACK_H
#define HIT_TRACK_H

/*

   Rob Kutschke, Sept 24, 1998.

   List of all tracking hits generated by mcfast.

   -------------------------------------------------------

   WARNING: if you change this file, also make sure you change 
            hit_track.inc !

   -------------------------------------------------------- 

*/


#include "hit_track_struct.h"

#define hit_trk_max 15000   /*  define the dimension parameter */

extern struct hit_trk_c {
  int hit_trk_num;                    /* Number of hits.  */
  int idm_httk;                       /* Alignment dummy. */
  hit_trk_s hit_trk[hit_trk_max];
} hit_trk_c_;

/* 
   For historical reasons the first item in the structure was sometimes
   called by this name, which should now be considered obsolete in
   all user code.
*/

#define n_obj_hit_trk hit_trk_num

#endif
/*
 *  $Id$
 *
 *  $Log$
 *  Revision 1.1  2000/06/19 19:58:37  eugenio
 *  Initial revision
 *
 *  Revision 1.2  1999/04/01 22:27:12  mcbride
 *   increase size for BTeV
 *
 * Revision 1.1  1998/09/25  02:43:18  kutschke
 * New file.  Generated from .inc version.
 *
 *
 */
