*****************************************************************************
*   User parameters
*****************************************************************************

      integer mcon
      parameter (mcon = 500)
      DFLOAT fcon          !User defined floating parameters
      integer icon         !User defined integer parameters

      common/con111/
     *  fcon(mcon),
     *  icon(mcon)
