#!/bin/sh
#   extract the Operating System Type using the uname
#   command. If we have SunOS, then we want to check
#   for either Solaris or 4.1.x:
#
OS=`uname`
#
if [ ${OS} = SunOS ]; then
#
#     OS is SunOS:
#     The following very ugly line will strip the firts number
#     off the OS type.
#
   TYPE=`uname -r | sed 's/\./ /g' | awk '{print $1}' `
#
   if [ ${TYPE} = 4 ]; then
      OS=${OS}${TYPE}
   fi
#
fi
#
echo ${OS}
