*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:23  eugenio
* Initial revision
*
* Revision 1.1.1.1  1994/04/05  21:31:29  lkg
* Beta version of GEANT in CLEO CVS format
*
*
*CMZ :          14/02/94  16.31.35  by  Lawrence Gibbons
*CMZ :          14/02/94  13.36.47  by  Lawrence Gibbons
* Increase declaration size of IQ and Q to allow for meaningful bounds checking
*CMZ :  3.15/09 07/04/92  14.40.14  by  Federico Carminati
*-- Author :
