*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:23  eugenio
* Initial revision
*
* Revision 1.2  1994/10/17  16:38:01  lkg
* Changed include statements to use partial path names.
*
* Revision 1.1.1.1  1994/04/05  21:31:30  lkg
* Beta version of GEANT in CLEO CVS format
*
*
*
* gccurs.inc
*
#if defined(CLEO_TYPE)
#include "geant/gcdes/gtcurs.inc"
#endif
      COMMON/GCCURS/INTFLA,SIZD2,FACHV,HALF,SAVPLX,SAVPLY,YPLT,XPLT
*
