*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:17  eugenio
* Initial revision
*
* Revision 1.1.1.1  1995/08/01  18:00:04  nk
* Consolidation
*
* Revision 1.1  1995/07/31 19:38:27  nk
* Added typscn
*
* Revision 1.1.1.1  1994/10/05  13:45:40  zfiles
* first version of typscn in CVS
*
*
*CMZ :  1.00/00 12/05/89  16.46.57  by  Ian C. Brock
*-- Author :
      CHARACTER*1 CNULL,CONES,CCTLZ,CTAB
      CHARACTER*2 CTABSP
      COMMON /TYPCHR/CNULL,CONES,CCTLZ,CTAB,CTABSP
