*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:17  eugenio
* Initial revision
*
* Revision 1.1.1.1  1995/08/01  18:00:04  nk
* Consolidation
*
* Revision 1.1  1995/07/31 19:38:29  nk
* Added typscn
*
* Revision 1.1.1.1  1994/10/05  13:45:40  zfiles
* first version of typscn in CVS
*
*
*CMZ :  1.00/00 12/05/89  16.46.57  by  Ian C. Brock
*-- Author :
      INTEGER DIMTYD,DIMSYM,DIMDEL,DIMCBF,DIMCLI,DIMWTY
      PARAMETER (DIMTYD = 255)
      PARAMETER (DIMSYM = 255)
      PARAMETER (DIMDEL = 255)
      PARAMETER (DIMCBF = 255)
      PARAMETER (DIMWTY = 255)
      PARAMETER (DIMCLI = 20)
