*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:17  eugenio
* Initial revision
*
* Revision 1.1.1.1  1995/08/01  18:00:04  nk
* Consolidation
*
* Revision 1.1  1995/07/31 19:38:31  nk
* Added typscn
*
* Revision 1.1.1.1  1994/10/05  13:45:40  zfiles
* first version of typscn in CVS
*
*
*CMZ :  1.00/00 12/05/89  16.46.57  by  Ian C. Brock
*-- Author :
C
      INTEGER IPOINT
      INTEGER NCHARS
      INTEGER KPOINT
      INTEGER KCHARS
      INTEGER NCHACC
C
      COMMON /TYPSCN/ IPOINT, NCHARS, KPOINT, KCHARS, NCHACC
