.TH DETPICK 1EXP
.SH NAME
DetPick
.SH DESCRIPTION
.PP
This module allows the user to find the name of a detector system
by picking on that object.  Warning! The object displayed is the first
object hit by the pick.  Only one object is chosen.  Please remember that many
detectors come in "families" as each layer is displayed as a separate object.
.SH INPUTS
.TP
.BI "Input Pick" " -- Pick"
This port accepts input as picked from the render.
.SH WIDGETS
.TP
.BI "detectors" " -- Scroll List"
The name of the object is displayed here.
.SH OUTPUTS
.TP
.BI "DetLabel" " -- Parameter"
This can be wired to the DetDisplay module to allow modification of the picked
object.
.SH KNOWN PROBLEMS
.PP
Make sure to position the pointer on the device you wish to change.  
.SH SEE ALSO
Render, DetDisplay
