.TH TRACEINFO 1EXP
.SH NAME
TraceInfo
.SH DESCRIPTION
.PP
This module displays information about picked traces
.SH INPUTS
.TP
.BI "InputHepLat" " -- Lattice (Opt.)"
Input with the HEP information and McFast information for display
.TP
.BI "hepnum" " -- Parameter"
The position of the particle to be displayed in the Hep list.
.SH WIDGETS
.TP
.BI "EventInfo" " -- Drawing Area"
Widget for displaying information
.SH KNOWN PROBLEMS
.PP
Current construction is awkward, requiring two inputs, one from TraceLat,
the other from TracePick
.SH SEE ALSO
TraceLat, TracePick
