****************************************************************************
*  List of unit numbers used by mcfast
****************************************************************************

      integer mcp_lout              !Fortran unit for mcp_fileout
      integer mcp_llpt              !Fortran unit for mcp_filelpt
      integer mcp_lhbk              !Fortran unit for Hbook output
      common/mcp_luns1/
     *  mcp_lout,
     *  mcp_llpt,
     *  mcp_lhbk
