*
* $Id$
*
* $Log$
* Revision 1.1  2000/06/19 20:00:50  eugenio
* Initial revision
*
* Revision 1.1.1.1  1994/10/08  02:21:32  zfiles
* first version of qqlib in CVS
*
*
*CMZ :  1.03/76 15/08/94  14.52.46  by  Peter C Kim
*CMZ :  1.03/15 18/07/91  16.20.24  by  Peter C Kim
*-- Author :    R.A.FULTON   14/01/91
#if defined(CLEO_CDGDOC)
C---------------------------------------------------------------
C   Variables in the JETSET73 commons
C
CXX      We renamed the variables N,K,P,V  --> NJS,KJS,PJS,VJS
CXX      so that /JET/ common can be liked at the same time.
C
C
C   LUJETS is now kept in GEANT.CMZ to avoid duplication. For now.
C
C     /LUJETX/ is used to convert /LUJETS/ --> /JET/
C---------------------------------------------------------------
#endif

